#spring.application.name=ElectricVehicles
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicles
    username: <user id>
    password: <********>
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true